Repository TYPO3-Documentation/TYPO3CMS-Reference-Typoscript, pull requests merged in 2022-08, with the labels that each got.

#568 Add warning for using the DatabaseQueryProcessor
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/DatabaseQueryProcessor.rst
Labels: backport-required, backport 11.5, backport 10.4

#571 [TASK] Remove outdated menuitems
  Documentation/MenuObjects/CommonItemStates/Index.rst
  Documentation/MenuObjects/CommonProperties/Index.rst
  Documentation/MenuObjects/Gmenu/Index.rst
  Documentation/MenuObjects/Gmenuitem/Index.rst
  Documentation/MenuObjects/Imgmenu/Index.rst
  Documentation/MenuObjects/Imgmenuitem/Index.rst
  Documentation/MenuObjects/Index.rst
  Documentation/MenuObjects/Sectionindex/Index.rst
  Documentation/MenuObjects/Tmenu/Index.rst
Labels: backport 11.5

#575 [TASK] Correct spelling of TYPO3 versions
  Documentation/Conditions/Index.rst
  Documentation/ContentObjects/Content/Index.rst
  Documentation/ContentObjects/Fluidtemplate/Index.rst
  Documentation/Functions/Select.rst
Labels: backport 11.5

#577 Change default rst indentation to 4 spaces
  .editorconfig
Labels: backport 11.5, backport 10.4

#580 Unify the layout of the rest of the Content objects
  Documentation/ContentObjects/Svg/Index.rst
  Documentation/ContentObjects/Text/Index.rst
  Documentation/ContentObjects/UserAndUserInt/Index.rst
Labels: backport 11.5
