Repository TYPO3-Documentation/TYPO3CMS-Reference-Typoscript, pull requests merged in 2023-09, with the labels that each got.

#789 [TASK] Adjust external includeCSSLibs example
  Documentation/Setup/Page/Index.rst
Labels: backport 11.5, backport 12.4

#792 [TASK] Remove deprecated code in SiteLanguage
  Documentation/Conditions/Index.rst
  Documentation/Functions/Data.rst
Labels: changelog

#797 [BUGFIX] Configure additional attributes with "includeJS"
  Documentation/Setup/Page/Index.rst
Labels: bug, backport 12.4

#800 [TASK] Use current TYPO3 logo for gifbuilder examples
  Documentation/Images/ThirdParty/GifbuilderExamples/Logo.png
  Documentation/Images/ThirdParty/GifbuilderExamples/Mask.png
  Documentation/Images/ThirdParty/GifbuilderExamples/Mask_i.png
  Documentation/Images/ThirdParty/GifbuilderExamples/Result.jpg
  Documentation/Images/ThirdParty/GifbuilderExamples/Typo3_shadow1.png
  Documentation/Images/ThirdParty/GifbuilderExamples/Typo3_shadow2.png
Labels: backport 11.5, backport 12.4

#803 [TASK] #101941 - Remove GIFBUILDER's reduceColors option
  Documentation/Gifbuilder/Gifbuilder/Index.rst
  Documentation/Gifbuilder/ObjectNames/Index.rst
Labels: changelog

#805 Fix links
  Documentation/Functions/Typolink.rst
Labels: backport 12.4

#807 [TASK] Check request object in conditions
  Documentation/Conditions/Index.rst
Labels: backport 11.5, backport 12.4
