Repository TYPO3-Documentation/TYPO3CMS-Reference-Typoscript, pull requests merged in 2023-10, with the labels that each got.

#810 Fix typo for page.parameters
  Documentation/Functions/Typolink.rst
Labels: backport 12.4

#812 [Feature] #94501 - FAL support for FlexFormProcessor
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/FlexFormProcessor.rst
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/_FlexFormWithFal.xml
Labels: changelog

#813 Add info that data.path resolves EXT: syntax
  Documentation/DataTypes/Index.rst
Labels: backport 11.5, backport 12.4

#817 [TASK] Improve format description of GIFBUILDER
  Documentation/Gifbuilder/ObjectNames/Index.rst
Labels: backport 11.5, backport 12.4

#816 [TASK] Revise Gibuilder/Gifbuilder chapter
  Documentation/Gifbuilder/Gifbuilder/Index.rst
  Documentation/Gifbuilder/Index.rst
Labels: backport 11.5, backport 12.4

#822 [BUGFIX] Correct header level in "Data / getText" chapter
  Documentation/Functions/Data.rst
Labels: backport 11.5, backport 12.4

#823 [TASK] Split GIFBUILDER objects into separate pages
  Documentation/Gifbuilder/ObjectNames/Adjust/Index.rst
  Documentation/Gifbuilder/ObjectNames/Box/Index.rst
  Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
  Documentation/Gifbuilder/ObjectNames/Effect/Index.rst
  Documentation/Gifbuilder/ObjectNames/Ellipse/Index.rst
  Documentation/Gifbuilder/ObjectNames/Emboss/Index.rst
  Documentation/Gifbuilder/ObjectNames/Image/Index.rst
  Documentation/Gifbuilder/ObjectNames/Index.rst
  Documentation/Gifbuilder/ObjectNames/Outline/Index.rst
  Documentation/Gifbuilder/ObjectNames/Properties/Index.rst
  Documentation/Gifbuilder/ObjectNames/Scale/Index.rst
  Documentation/Gifbuilder/ObjectNames/Shadow/Index.rst
  Documentation/Gifbuilder/ObjectNames/Text/Index.rst
  Documentation/Gifbuilder/ObjectNames/Workarea/Index.rst
Labels: content structure, backport 11.5, backport 12.4

#824 [TASK] Modernize GIFBUILDER example
  Documentation/Gifbuilder/Gifbuilder/Index.rst
  Documentation/Images/ManualScreenshots/FrontendOutput/Gifbuilder/typo3-gifbuilder-example.png
Labels: backport 11.5, backport 12.4

#831 [TASK] GIFBUILDER's TEXT.text property allows a fixed string
  Documentation/Gifbuilder/ObjectNames/Text/Index.rst
Labels: backport 11.5, backport 12.4

#835 [TASK] Revise GIFBUILDER examples chapter
  Documentation/Gifbuilder/Examples.rst
Labels: backport 11.5, backport 12.4

#836 [TASK] Remove GIFBUILDER's IMGMAP documentation
  Documentation/Gifbuilder/NonGifbuilderObject/Index.rst
  Documentation/Gifbuilder/ObjectNames/Text/Index.rst
Labels: backport 11.5, backport 12.4

#837 [TASK] Rename chapter "Object names in this section"
  Documentation/Gifbuilder/ObjectNames/Index.rst
Labels: backport 11.5, backport 12.4

#849 [TASK] Remove outdated hint to activate GFX|gdlib_png
  Documentation/Gifbuilder/Examples.rst
Labels: changelog
