Repository TYPO3-Documentation/TYPO3CMS-Reference-Typoscript, pull requests merged in 2023-12, with the labels that each got.

#921 [TASK] Streamline config.contentObjectExceptionHandler
  Documentation/Setup/Config/Index.rst
Labels: backport 11.5, backport 12.4

#925 [BUGFIX] Reintroduce label
  Documentation/Functions/Stdwrap.rst
Labels: backport 11.5, backport 12.4

#922 [TASK] #102605 - TSFE->fe_user removed
  Documentation/AppendixA/Index.rst
Labels: changelog

#927 [TASK] Use captions for code snippets
  Documentation/UsingSetting/AddTypoScriptWithExtensions.rst
Labels: backport 11.5, backport 12.4

#928 [TASK] Add links to "Access TypoScript" chapter
  Documentation/UsingSetting/AccessTypoScriptWithExtensions.rst
Labels: backport 11.5, backport 12.4

#929 [TASK] Replace "t3-data-type" with "confval"
  Documentation/ContentObjects/Content/Index.rst
  Documentation/ContentObjects/Extbaseplugin/Index.rst
  Documentation/ContentObjects/Hmenu/Categories.rst
  Documentation/ContentObjects/Image/Index.rst
  Documentation/ContentObjects/Svg/Index.rst
  Documentation/ContentObjects/UserAndUserInt/Index.rst
  Documentation/DataTypes/Index.rst
  Documentation/Functions/Cache.rst
  Documentation/Functions/Data.rst
  Documentation/Functions/Encapslines.rst
  Documentation/Functions/Htmlparser.rst
  Documentation/Functions/HtmlparserTags.rst
  Documentation/Functions/If.rst
  Documentation/Functions/Imagelinkwrap.rst
  Documentation/Functions/Imgresource.rst
  Documentation/Functions/Index.rst
  Documentation/Functions/Makelinks.rst
  Documentation/Functions/Numberformat.rst
  Documentation/Functions/Parsefunc.rst
  Documentation/Functions/Replacement.rst
  Documentation/Functions/Round.rst
  Documentation/Functions/Select.rst
  Documentation/Functions/Split.rst
  Documentation/Functions/Stdwrap.rst
  Documentation/Functions/Strpad.rst
  Documentation/Functions/Tags.rst
  Documentation/Functions/Typolink.rst
  Documentation/Gifbuilder/ObjectNames/Box/Index.rst
  Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
  Documentation/Gifbuilder/ObjectNames/Ellipse/Index.rst
  Documentation/Gifbuilder/ObjectNames/Emboss/Index.rst
  Documentation/Gifbuilder/ObjectNames/Image/Index.rst
  Documentation/Gifbuilder/ObjectNames/Outline/Index.rst
  Documentation/Gifbuilder/ObjectNames/Shadow/Index.rst
  Documentation/Gifbuilder/ObjectNames/Text/Index.rst
  Documentation/Gifbuilder/Properties.rst
  Documentation/Settings.cfg
  Documentation/Setup/Config/Index.rst
  Documentation/Setup/Page/Index.rst
  Documentation/TopLevelObjects/Plugin.rst
  Documentation/UsingSetting/Constants.rst
Labels: backport 11.5, backport 12.4

#930 [TASK] Replace "aspect" with confval in "Conditions" chapter
  Documentation/Conditions/Index.rst
Labels: backport 11.5, backport 12.4

#931 [TASK] Replace "aspect" role in cObject chapter
  Documentation/ContentObjects/Index.rst
Labels: backport 11.5, backport 12.4

#941 [TASK] #100405 - Deprecate property TypoScriptFrontendController->type
  Documentation/AppendixA/Index.rst
Labels: changelog, backport 12.4

#943 [TASK] #102547 - Avoid TSFE->type
  Documentation/AppendixA/Index.rst
Labels: changelog

#944 [TASK] #102621 - TSFE members marked as read-only
  Documentation/AppendixA/Index.rst
Labels: changelog

#945 [TASK] Replace "t3-data-processor-csv" with "confval"
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/CommaSeparatedValueProcessor.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#946 [TASK] #102621 - TSFE->getPageArguments() marked as internal
  Documentation/AppendixA/Index.rst
Labels: changelog

#949 [TASK] Replace "t3-data-processor-db" with "confval"
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/DatabaseQueryProcessor.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#952 [TASK] Replace "t3-data-processor-files" with "confval"
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/FilesProcessor.rst
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/GalleryProcessor.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#953 [TASK] #102715 - Add alternatives for TSFE properties
  Documentation/AppendixA/Index.rst
Labels: changelog

#956 [TASK] Replace "t3-data-processor-flex" with "confval"
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/FlexFormProcessor.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#959 [TASK] Replace "t3-data-processor-gallery" with "confval"
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/GalleryProcessor.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#962 [TASK] Replace "t3-data-processor-lang" with "confval"
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/LanguageMenuProcessor.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#965 [TASK] Replace "t3-data-processor-menu" with "confval"
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/MenuProcessor.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#968 [TASK] Replace "t3-data-processor-sitelang" with "confval"
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/SiteLanguageProcessor.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#970 [TASK] Replace "t3-data-processor-site" with "confval"
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/SiteProcessor.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#973 [TASK] Replace "t3-data-processor-split" with "confval"
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/SplitProcessor.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#976 [TASK] Replace "t3-cobj-text" with "confval"
  Documentation/ContentObjects/Text/Index.rst
  Documentation/Functions/Stdwrap.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#979 [TASK] Replace "t3-cobj-coa" with "confval"
  Documentation/ContentObjects/CoaAndCoaInt/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#982 [TASK] Replace "t3-cobj-case" with "confval"
  Documentation/ContentObjects/Case/Index.rst
  Documentation/ContentObjects/CoaAndCoaInt/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#985 [TASK] Replace "t3-cobj-content" with "confval"
  Documentation/ContentObjects/Content/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#988 [TASK] Replace "t3-cobj-extbaseplugin" with "confval"
  Documentation/ContentObjects/Extbaseplugin/Index.rst
  Documentation/Settings.cfg
Labels: backport 12.4
