Repository TYPO3-Documentation/TYPO3CMS-Reference-Typoscript, pull requests merged in 2023-11, with the labels that each got.

#852 [TASK] Revise GIFBUILDER object CROP
  Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
  Documentation/Gifbuilder/ObjectNames/Properties/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#853 [TASK] Dissolve Gifbuilder/Gifbuilder chapter
  Documentation/Gifbuilder/Calc.rst
  Documentation/Gifbuilder/Index.rst
Labels: content structure, backport 11.5, backport 12.4

#858 [TASK] Revise GIFBUILDER object EFFECT
  Documentation/Gifbuilder/ObjectNames/Effect/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#859 [TASK] Move GIFBUILDER Properties page
  Documentation/Gifbuilder/Index.rst
  Documentation/Gifbuilder/ObjectNames/Index.rst
  Documentation/Gifbuilder/Properties.rst
Labels: backport 11.5, backport 12.4

#864 [TASK] Revise GIFBUILDER object ELLIPSE
  Documentation/Gifbuilder/ObjectNames/Ellipse/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#868 [TASK] Revise GIFBUILDER object EMBOSS
  Documentation/Gifbuilder/ObjectNames/Emboss/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#873 [TASK] Revise GIFBUILDER object IMAGE
  Documentation/Gifbuilder/ObjectNames/Image/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#876 [TASK] Revise GIFBUILDER object OUTLINE
  Documentation/Gifbuilder/ObjectNames/Outline/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#879 [BUGFIX] Add missing caption to GIFBUILDER's OUTLINE.color property
  Documentation/Gifbuilder/ObjectNames/Outline/Index.rst
Labels: backport 11.5, backport 12.4

#880 [TASK] Revise GIFBUILDER object SCALE
  Documentation/Gifbuilder/ObjectNames/Scale/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#886 [TASK] #98312 - TypoScript setting page.CSS_inlineStyle removed
  Documentation/Setup/Page/Index.rst
Labels: changelog, backport 12.4

#887 [TASK] Revise GIFBUILDER object SHADOW
  Documentation/Gifbuilder/ObjectNames/Shadow/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#888 [TASK] Revise GIFBUILDER properties
  Documentation/Gifbuilder/ObjectNames/Text/Index.rst
  Documentation/Gifbuilder/Properties.rst
Labels: backport 11.5, backport 12.4

#894 [TASK] Revise GIFBUILDER object WORKAREA
  Documentation/Gifbuilder/ObjectNames/Workarea/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#897 [TASK] Revise GIFBUILDER object TEXT
  Documentation/Gifbuilder/ObjectNames/Text/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#900 [TASK] Use custom types for linking object properties in GIFBUILDER chapter
  Documentation/Gifbuilder/Examples.rst
  Documentation/Gifbuilder/ObjectNames/Adjust/Index.rst
  Documentation/Gifbuilder/ObjectNames/Box/Index.rst
  Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
  Documentation/Gifbuilder/ObjectNames/Effect/Index.rst
  Documentation/Gifbuilder/ObjectNames/Emboss/Index.rst
  Documentation/Gifbuilder/ObjectNames/Shadow/Index.rst
  Documentation/Gifbuilder/ObjectNames/Text/Index.rst
  Documentation/Gifbuilder/Properties.rst
Labels: backport 11.5, backport 12.4

#903 [TASK] Introduce custom types for GIFBUILDER properties
  Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
  Documentation/Gifbuilder/ObjectNames/Scale/Index.rst
  Documentation/Gifbuilder/Properties.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#904 Add label for addPageCacheTags again
  Documentation/Functions/Stdwrap.rst
Labels: backport 12.4

#909 [FEATURE] #102177 - Add WebP support for GIFBUILDER
  Documentation/Gifbuilder/Properties.rst
Labels: changelog

#910 Fix variable name for userGroupIds
  Documentation/Conditions/Index.rst
Labels: backport 11.5, backport 12.4

#913 Subpart cache tags are now being propagated to page cache tags
  Documentation/Functions/Cache.rst
Labels: backport 12.4

#915 [TASK] Use confval instead of custom t3-gifbuilder-... directives
  Documentation/Gifbuilder/Examples.rst
  Documentation/Gifbuilder/ObjectNames/Adjust/Index.rst
  Documentation/Gifbuilder/ObjectNames/Box/Index.rst
  Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
  Documentation/Gifbuilder/ObjectNames/Effect/Index.rst
  Documentation/Gifbuilder/ObjectNames/Ellipse/Index.rst
  Documentation/Gifbuilder/ObjectNames/Emboss/Index.rst
  Documentation/Gifbuilder/ObjectNames/Image/Index.rst
  Documentation/Gifbuilder/ObjectNames/Outline/Index.rst
  Documentation/Gifbuilder/ObjectNames/Scale/Index.rst
  Documentation/Gifbuilder/ObjectNames/Shadow/Index.rst
  Documentation/Gifbuilder/ObjectNames/Text/Index.rst
  Documentation/Gifbuilder/ObjectNames/Workarea/Index.rst
  Documentation/Gifbuilder/Properties.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4
