Repository TYPO3-Documentation/TYPO3CMS-Reference-Typoscript, pull requests merged in 2023-08, with the labels that each got.

#770 Add example for numRows
  Documentation/Functions/Numrows.rst
Labels: backport 11.5, backport 12.4

#772 [TASK] #100963 - Adjust hint for now removed TSFE properties
  Documentation/Functions/Data.rst
Labels: changelog

#773 [TASK] Adjust data type formatting for config.spamProtectEmailAddresses
  Documentation/Setup/Config/Index.rst
Labels: backport 12.4

#776 Optimize the links on select page
  Documentation/Functions/Select.rst
Labels: backport 11.5, backport 12.4

#783 [TASK] Revise the conditions chapter
  Documentation/Conditions/Index.rst
Labels: backport 12.4
