Repository TYPO3-Documentation/TYPO3CMS-Reference-Typoscript, pull requests merged in 2024-05, with the labels that each got.

#1241 Overhaul Fluidtemplate
  Documentation/ContentObjects/Fluidtemplate/Index.rst
Labels: backport 11.5, backport 12.4

#1243 [TASK] cObjects with confval tables
  Documentation/ContentObjects/Case/Index.rst
  Documentation/ContentObjects/CoaAndCoaInt/Index.rst
  Documentation/ContentObjects/Content/Index.rst
  Documentation/ContentObjects/Extbaseplugin/Index.rst
  Documentation/ContentObjects/Files/Index.rst
  Documentation/ContentObjects/Fluidtemplate/Index.rst
  Documentation/ContentObjects/Image/Index.rst
  Documentation/ContentObjects/ImgResource/Index.rst
  Documentation/ContentObjects/LoadRegister/Index.rst
  Documentation/ContentObjects/Records/Index.rst
  Documentation/ContentObjects/Svg/Index.rst
  Documentation/ContentObjects/Text/Index.rst
  Documentation/ContentObjects/UserAndUserInt/Index.rst
Labels: backport 11.5, backport 12.4

#1245 [TASK] HMENU with confval tables
  Documentation/ContentObjects/Hmenu/Browse.rst
  Documentation/ContentObjects/Hmenu/Categories.rst
  Documentation/ContentObjects/Hmenu/Directory.rst
  Documentation/ContentObjects/Hmenu/Index.rst
  Documentation/ContentObjects/Hmenu/Keywords.rst
  Documentation/ContentObjects/Hmenu/Language.rst
  Documentation/ContentObjects/Hmenu/List.rst
  Documentation/ContentObjects/Hmenu/Rootline.rst
  Documentation/ContentObjects/Hmenu/Tmenu/Index.rst
  Documentation/ContentObjects/Hmenu/Tmenu/Tmenuitem.rst
  Documentation/ContentObjects/Hmenu/Updated.rst
  Documentation/ContentObjects/Hmenu/Userfunction.rst
  Documentation/Setup/Config/Index.rst
Labels: backport 12.4

#1246 [TASK] Refactor Plugin page
  Documentation/TopLevelObjects/Plugin.rst
Labels: backport 12.4

#1248 [TASK] Refactor CONFIG page
  Documentation/Setup/Config/Index.rst
Labels: backport 12.4

#1249 [TASK] Move config and page in with top level objects
  Documentation/TopLevelObjects/Config.rst
  Documentation/TopLevelObjects/Index.rst
  Documentation/TopLevelObjects/Page/Examples.rst
  Documentation/TopLevelObjects/Page/Index.rst
Labels: backport 12.4

#1254 fix typo with includeJS / includeCSSLibs
  Documentation/TopLevelObjects/Page/Index.rst
Labels: backport 12.4

#1256 [TASK] Move Dataprocessing.rst to Dataprocessing/Index.rst
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/Index.rst
  Documentation/ContentObjects/Fluidtemplate/Index.rst
Labels: backport 11.5, backport failed, backport 12.4

#1261 [TASK] Add documentation for extbase newRecordStoragePid setting
  Documentation/TopLevelObjects/Plugin.rst
Labels: backport 11.5, backport 12.4

#1262 [TASK] Introduce `Build/Scripts/runTests.sh`
  .github/workflows/tests.yml
  Build/.gitignore
  Build/.php-cs-fixer.dist.php
  Build/Scripts/runTests.sh
  Documentation/CodeSnippets/Config/DataProcessing.php
  Documentation/CodeSnippets/Config/Menus.php
  Documentation/UsingSetting/_Sets/_TcaOverridesSystemplateV12.php
  Documentation/UsingSetting/_Sets/_ext_localconf.php
  Documentation/codesnippets.php
  Makefile
  composer.json
Labels: backport-required
