Repository TYPO3-Documentation/TYPO3CMS-Reference-Typoscript, pull requests merged in 2024-04, with the labels that each got.

#1165 [TASK] Overhaul data / gettext chapter
  Documentation/Functions/Data.rst
Labels: backport 11.5, backport 12.4

#1166 [TASK] Overhaul PAGE chapter
  Documentation/Setup/Page/Index.rst
Labels: backport 11.5, backport 12.4

#1169 [TASK] Overhaul functions overview pager
  Documentation/Functions/Index.rst
Labels: backport 11.5, backport 12.4

#1172 [TASK] Overhaul HMENU browse page
  Documentation/ContentObjects/Hmenu/Browse.rst
Labels: backport 11.5, backport 12.4

#1174 [TASK] Overhaul HMENU directory page
  Documentation/ContentObjects/Hmenu/Directory.rst
Labels: backport 11.5, backport 12.4

#1175 [TASK] Overhaul HMENU Keywords page
  Documentation/ContentObjects/Hmenu/Keywords.rst
Labels: backport 11.5, backport 12.4

#1167 [TASK] Overhaul module chapter
  Documentation/TopLevelObjects/Module.rst
Labels: backport 11.5, backport 12.4

#1176 [TASK] Overhaul HMENU Language page
  Documentation/ContentObjects/Hmenu/Language.rst
Labels: backport 11.5, backport 12.4

#1177 [TASK] Overhaul HMENU root line page
  Documentation/ContentObjects/Hmenu/Rootline.rst
Labels: backport 11.5, backport 12.4

#1186 [TASK] Overhaul HMENU updated page
  Documentation/ContentObjects/Hmenu/Userfunction.rst
  Documentation/Images/ManualScreenshots/FrontendOutput/Hmenu/ContentObjectsHmenuExampleMenu.png
Labels: backport 11.5, backport 12.4

#1194 Set permalink for optionSplit ruleset
  Documentation/Functions/OptionSplit.rst
Labels: backport 11.5, backport 12.4

#1197 Set all other permalinks in Option Split file
  Documentation/Functions/OptionSplit.rst
Labels: backport 11.5, backport 12.4

#1201 [TASK] Overhaul HMENU updated page
  Documentation/ContentObjects/Hmenu/Updated.rst
Labels: backport 11.5, backport 12.4

#1200 [TASK] Overhaul plugin page
  Documentation/TopLevelObjects/Plugin.rst
Labels: backport 11.5, backport 12.4

#1202 [TASK] Overhaul HMENU List page
  Documentation/ContentObjects/Hmenu/List.rst
Labels: backport 11.5, backport 12.4

#1209 Removed unnecessary new line
  Documentation/ContentObjects/Fluidtemplate/Index.rst
Labels: backport 11.5, backport 12.4

#1208 [TASK] Overhaul appendix page
  Documentation/AppendixA/Index.rst
Labels: backport 11.5, backport 12.4

#1203 [TASK] Overhaul other reserved toplevel objects page
  Documentation/TopLevelObjects/Other.rst
Labels: backport 11.5, backport 12.4

#1216 Fix markup for defer (#1215)
  Documentation/Setup/Page/Index.rst
Labels: backport 12.4

#1220 [TASK] Add ServerRequestInterface to USER/userFunc
  Documentation/ContentObjects/UserAndUserInt/Index.rst
Labels: backport 11.5, backport 12.4

#1213 [FEATURE] #100405 - Add data function "request"
  Documentation/Functions/Data.rst
Labels: content missing, backport 12.4

#1225 [TASK] Streamline array usage examples in data function
  Documentation/Functions/Data.rst
  Documentation/Functions/Imagelinkwrap.rst
Labels: backport 11.5, backport 12.4

#1227 [BUGFIX] Add missing cache property to content elements
  Documentation/ContentObjects/Extbaseplugin/Index.rst
  Documentation/ContentObjects/Files/Index.rst
  Documentation/ContentObjects/Fluidtemplate/Index.rst
  Documentation/ContentObjects/Image/Index.rst
  Documentation/ContentObjects/ImgResource/Index.rst
  Documentation/ContentObjects/Svg/Index.rst
Labels: backport 11.5, backport 12.4

#1232 [TASK] Use glob for content objects menu
  Documentation/ContentObjects/Index.rst
Labels: backport 11.5, backport 12.4

#1230 [TASK] Move the TMENU as subpage of the HMENU
  Documentation/ContentObjects/Hmenu/Index.rst
  Documentation/ContentObjects/Hmenu/Tmenu/Index.rst
  Documentation/ContentObjects/Hmenu/Tmenu/Tmenuitem.rst
  Documentation/Index.rst
  Documentation/MenuObjects/Index.rst
Labels: backport 11.5, backport 12.4

#1237 [BUGFIX] Resolve duplicate link anchors
  Documentation/DataTypes/Index.rst
  Documentation/Functions/Htmlparser.rst
  Documentation/Functions/OptionSplit.rst
  Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
  Documentation/Gifbuilder/ObjectNames/Ellipse/Index.rst
  Documentation/Setup/Page/Index.rst
Labels: backport 11.5, backport 12.4
