Repository TYPO3-Documentation/TYPO3CMS-Reference-Typoscript, pull requests merged in 2024-11, with the labels that each got.

#1395 [TASK] Avoid the term "template" for TypoScript
  Documentation/Guide/ReadingContentRecords/ContentElements/Index.rst
  Documentation/Guide/TypoScriptFunctions/Typolink/Index.rst
  Documentation/Guide/TypoScriptOverview/BackendConfiguration/Index.rst
  Documentation/Guide/TypoScriptOverview/FirstSteps/Index.rst
  Documentation/Guide/TypoScriptOverview/MainTemplate/Index.rst
  Documentation/Guide/TypoScriptOverview/TheTermTemplate/Index.rst
  Documentation/Guide/UsingFluidStyledContent/Index.rst
  Documentation/Guide/UsingStdWrap/HeedTheOrder/Index.rst
  Documentation/Guide/UsingStdWrap/TheDataType/Index.rst
  Documentation/Images/AutomaticScreenshots/TemplateAnalyzerStructure.png
  Documentation/Images/AutomaticScreenshots/TemplateAnalyzerStructure.rst.txt
  Documentation/Images/ManualScreenshots/IncludedTypoScript.png
  Documentation/Images/ManualScreenshots/NoTypoScriptTemplateFound.png
Labels: backport 12.4, backport 13.4

#1399 [TASK] Combine chapter Guide Overview into one page
  Documentation/AppendixA/Index.rst
  Documentation/Guide/Index.rst
  Documentation/Guide/ReadingContentRecords/Index.rst
  Documentation/Guide/ReadingContentRecords/_Chapters/_ContentElements.rst.txt
  Documentation/Guide/ReadingContentRecords/_snippets/_Layout.html
  Documentation/Guide/ReadingContentRecords/_snippets/_PAGE.typoscript
  Documentation/Guide/ReadingContentRecords/_snippets/_lib.contentElement.typoscript
  Documentation/Guide/ReadingContentRecords/_snippets/_tt_content.header.typoscript
  Documentation/Guide/ReadingContentRecords/_snippets/_tt_content.typoscript
  Documentation/Guide/TypoScriptFunctions/GetText/Index.rst
  Documentation/Guide/TypoScriptFunctions/Index.rst
  Documentation/Guide/TypoScriptFunctions/StdWrap/Index.rst
  Documentation/Guide/TypoScriptFunctions/StdWrap/_Chapters/_CObject.rst.txt
  Documentation/Guide/TypoScriptFunctions/StdWrap/_Chapters/_HeedTheOrder.rst.txt
  Documentation/Guide/TypoScriptFunctions/StdWrap/_Chapters/_ModifyTheOrder.rst.txt
  Documentation/Guide/TypoScriptFunctions/StdWrap/_Chapters/_TheDataType.rst.txt
  Documentation/Guide/TypoScriptFunctions/StdWrap/_snippets/_cObject.typoscript
  Documentation/Guide/TypoScriptFunctions/StdWrap/_snippets/_order.typoscript
  Documentation/Guide/TypoScriptFunctions/StdWrap/_snippets/_orderedStdWrap.typoscript
  Documentation/Guide/TypoScriptOverview/Index.rst
  Documentation/Guide/TypoScriptOverview/TheTermTemplate/_page.typoscript
  Documentation/Guide/TypoScriptOverview/_Chapters/_BackendConfiguration.rst.txt
  Documentation/Guide/TypoScriptOverview/_Chapters/_FirstSteps.rst.txt
  Documentation/Guide/TypoScriptOverview/_Chapters/_MainTemplate.rst.txt
  Documentation/Guide/TypoScriptOverview/_Chapters/_Prerequisites.rst.txt
  Documentation/Guide/TypoScriptOverview/_Chapters/_TheTermTemplate.rst.txt
  Documentation/Guide/TypoScriptOverview/_Chapters/_TypoScriptAnArray.rst.txt
  Documentation/Guide/TypoScriptOverview/_Chapters/_WhyTypoScript.rst.txt
  Documentation/Guide/TypoScriptOverview/_snippets/_mypage.php
  Documentation/Guide/TypoScriptOverview/_snippets/_mypage.typoscript
  Documentation/Guide/TypoScriptOverview/_snippets/_mypage2.typoscript
  Documentation/Guide/TypoScriptOverview/_snippets/_mypage3.typoscript
  Documentation/Guide/TypoScriptOverview/_snippets/_mypage4.typoscript
  Documentation/Guide/TypoScriptOverview/_snippets/_mypage5.typoscript
  Documentation/Guide/TypoScriptOverview/_snippets/_page.php
  Documentation/Guide/TypoScriptOverview/_snippets/_page.typoscript
  Documentation/Guide/TypoScriptOverview/_snippets/_page1.typoscript
  Documentation/Guide/UsingFluidStyledContent/Index.rst
  Documentation/Index.rst
Labels: backport 12.4, backport 13.4

#1403 [TASK] Adjust TypoScript Syntax links
  Documentation/About.rst
  Documentation/Conditions/Index.rst
  Documentation/Glossary.rst
  Documentation/Guide/Index.rst
  Documentation/Guide/NextSteps/Index.rst
  Documentation/Guide/TypoScriptOverview/_Chapters/_FirstSteps.rst.txt
  Documentation/Index.rst
  Documentation/Introduction/Index.rst
  Documentation/Syntax/FileImports/Index.rst
  Documentation/TopLevelObjects/Index.rst
  Documentation/TopLevelObjects/Other.rst
  Documentation/UsingSetting/Constants.rst
  Documentation/UsingSetting/Entering.rst
Labels: backport 12.4, backport 13.4

#1405 [TASK] Reorder the chapters in the guide
  Documentation/Guide/Content/Index.rst
  Documentation/Guide/Content/_Chapters/_ContentElements.rst.txt
  Documentation/Guide/Content/_Chapters/_HtmlTemplate.rst.txt
  Documentation/Guide/Content/_snippets/_FLUIDTEMPLATE.typoscript
  Documentation/Guide/Content/_snippets/_Fluid.html
  Documentation/Guide/Content/_snippets/_Layout.html
  Documentation/Guide/Content/_snippets/_PAGE.typoscript
  Documentation/Guide/Content/_snippets/_lib.contentElement.typoscript
  Documentation/Guide/Content/_snippets/_tt_content.header.typoscript
  Documentation/Guide/Content/_snippets/_tt_content.typoscript
  Documentation/Guide/FirstSteps/Index.rst
  Documentation/Guide/FirstSteps/_snippets/_mypage.php
  Documentation/Guide/FirstSteps/_snippets/_mypage.typoscript
  Documentation/Guide/FirstSteps/_snippets/_mypage2.typoscript
  Documentation/Guide/FirstSteps/_snippets/_mypage3.typoscript
  Documentation/Guide/FirstSteps/_snippets/_mypage4.typoscript
  Documentation/Guide/FirstSteps/_snippets/_mypage5.typoscript
  Documentation/Guide/Index.rst
  Documentation/Guide/Menu/Index.rst
  Documentation/Guide/Menu/_lib.textmenu.typoscript
  Documentation/Guide/Menu/_menu.html
  Documentation/Guide/Overview/Index.rst
  Documentation/Guide/Overview/_Chapters/_BackendConfiguration.rst.txt
  Documentation/Guide/Overview/_Chapters/_MainTemplate.rst.txt
  Documentation/Guide/Overview/_Chapters/_Prerequisites.rst.txt
  Documentation/Guide/Overview/_Chapters/_TheTermTemplate.rst.txt
  Documentation/Guide/Overview/_Chapters/_TypoScriptAnArray.rst.txt
  Documentation/Guide/Overview/_Chapters/_WhyTypoScript.rst.txt
  Documentation/Guide/Overview/_snippets/_page.php
  Documentation/Guide/Overview/_snippets/_page.typoscript
  Documentation/Guide/Overview/_snippets/_page1.typoscript
Labels: backport 12.4, backport 13.4

#1396 Add new subkeys for siteLanguage.locale in Data.rst (#1373)
  Documentation/Functions/Data.rst
Labels: backport 13.4

#1404 [FEATURE] Add chapter about PAGE to the TS guide
  Documentation/Guide/Content/_snippets/_FLUIDTEMPLATE.typoscript
  Documentation/Guide/FirstSteps/Index.rst
  Documentation/Guide/FirstSteps/_snippets/_mypage.php
  Documentation/Guide/FirstSteps/_snippets/_mypage.typoscript
  Documentation/Guide/FirstSteps/_snippets/_mypage2.typoscript
  Documentation/Guide/FirstSteps/_snippets/_mypage3.typoscript
  Documentation/Guide/FirstSteps/_snippets/_mypage4.typoscript
  Documentation/Guide/FirstSteps/_snippets/_mypage5.typoscript
  Documentation/Guide/Index.rst
  Documentation/Guide/Overview/_Chapters/_TheTermTemplate.rst.txt
  Documentation/Guide/Page/Index.rst
  Documentation/Guide/Page/_Default.html
  Documentation/Guide/Page/_css-loading.typoscript
  Documentation/Guide/Page/_favicon.typoscript
  Documentation/Guide/Page/_fluid-template.typoscript
  Documentation/Guide/Page/_hello-world.typoscript
  Documentation/Guide/Page/_javascript-loading.typoscript
  Documentation/Guide/Page/_tracking-code.typoscript
  Documentation/TopLevelObjects/Page/Index.rst
Labels: backport 12.4, backport 13.4

#1413 Add more explaination for TS:data SiteLanguage:locale #1409
  Documentation/Functions/Data.rst
Labels: backport 12.4, backport 13.4

#1416 [BUGFIX] jumbotrong -> jumbotron
  Documentation/DataProcessing/_PageContentFetchingProcessor/_Default.html
Labels: backport 13.4

#1415 [BUGFIX] In PAGEVIEW rootpage is found in site not page
  Documentation/ContentObjects/Pageview/_includes/_LinkToRootPage.html
Labels: backport 13.4

#1410 [FEATURE] Explain menu rendering with data processors
  Documentation/Guide/Menu/Index.rst
  Documentation/Guide/Menu/_MenuTemplate.html
  Documentation/Guide/Menu/_lib.textmenu.typoscript
  Documentation/Guide/Menu/_menu.html
  Documentation/Guide/Menu/_menu.typoscript
Labels: backport 12.4, backport 13.4

#1337 [TASK] Add missing page.meta attribute sub-property
  Documentation/TopLevelObjects/Page/Index.rst
Labels: backport 12.4, backport 13.4

#1422 [BUGFIX] Avoid hint to temp. in styles. TLO
  Documentation/TopLevelObjects/Other.rst
Labels: backport 12.4, backport 13.4

#1425 Remove the section for the TLO “temp.” as no unset() is executed anymore
  Documentation/TopLevelObjects/Index.rst
  Documentation/TopLevelObjects/Other.rst
Labels: backport 12.4, backport 13.4

#1428 fix: avoid backslash in type values
  Documentation/Functions/Select.rst
Labels: backport 12.4, backport 13.4

#1421 [TASK] cObject retrieves raw record automatically
  Documentation/DataProcessing/PageContentFetchingProcessor.rst
  Documentation/DataProcessing/_PageContentFetchingProcessor/_Default.html
Labels: changelog, backport 13.4

#1435 [TASK] Change references previously going to tsconfig
  Documentation/About.rst
  Documentation/Functions/Stdwrap.rst
  Documentation/Functions/Typolink.rst
  Documentation/Guide/Index.rst
  Documentation/Index.rst
  Documentation/Syntax/Conditions/Index.rst
  Documentation/Syntax/FileImports/Index.rst
  Documentation/TopLevelObjects/Module.rst
  Documentation/UserTsconfig/Options.rst
  Documentation/UsingSettingTSconfig/_PageTSconfig/_pages.php
  Documentation/UsingSettingTSconfig/_PhpApi/_MyBackendLoggedInController.php
Labels: backport 12.4, backport 13.4

#1437 Add notice about preventing XSS in TMENU
  Documentation/ContentObjects/Hmenu/Tmenu/Index.rst
Labels: backport 12.4, backport 13.4

#1441 [TASK] Move constant editor into backend module page
  Documentation/UsingSetting/Entering.rst
  Documentation/UsingSetting/Index.rst
  Documentation/UsingSetting/TheConstantEditor.rst
Labels: backport 13.4

#1444 [TASK] Remove outdated about page
  Documentation/About.rst
  Documentation/Index.rst
  Documentation/Introduction/Index.rst
Labels: backport 12.4, backport 13.4

#1447 [TASK] Update introduction
  Documentation/Introduction/Index.rst
Labels: backport 12.4, backport 13.4

#1450 Update tree.pagelayout for multiple
  Documentation/Conditions/Index.rst
Labels: backport 12.4, backport 13.4

#1454 Mention "in" strict comparison for tree.pagelayout
  Documentation/Conditions/Index.rst
Labels: backport 12.4, backport 13.4
