Repository TYPO3-Documentation/TYPO3CMS-Reference-Typoscript, pull requests merged in 2024-03, with the labels that each got.

#1082 [TASK] Replace "t3-function-if" with "confval"
  Documentation/Functions/If.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#1084 [TASK] Replace "t3-function-imagelinkwrap" with "confval"
  Documentation/Functions/Imagelinkwrap.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#1086 [TASK] Replace "t3-function-imgresource" with "confval"
  Documentation/Functions/Imgresource.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#1088 [TASK] Replace "t3-function-makelinks" with "confval"
  Documentation/Functions/Makelinks.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#1090 [TASK] Replace "t3-function-numberformat" with "confval"
  Documentation/Functions/Numberformat.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#1092 [TASK] Replace "t3-function-numrows" with "confval"
  Documentation/Functions/Numrows.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#1094 [TASK] Replace "t3-function-parsefunc" with "confval"
  Documentation/Functions/Parsefunc.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#1096 [BUGFIX] Correct reference to TYPO3_CONF_VARS['SYS'] chapter in TYPO3 Explained
  Documentation/Conditions/Index.rst
Labels: backport 11.5, backport 12.4

#1095 [BUGFIX] Correct reference to backend layout chapter in TYPO3 Explained
  Documentation/Conditions/Index.rst
Labels: backport 11.5, backport 12.4

#1102 [TASK] Replace "t3-function-replacement "confval" (#1094)
  Documentation/Functions/Replacement.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#1104 [TASK] Replace "t3-function-round" with "confval"
  Documentation/Functions/Round.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#1106 [TASK] Replace "t3-function-select" with "confval"
  Documentation/Functions/Select.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#1107 [BUGFIX] Correct more references
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/FlexFormProcessor.rst
  Documentation/Introduction/Index.rst
  Documentation/TopLevelObjects/Module.rst
Labels: backport 11.5, backport 12.4

#1111 [TASK] Replace "t3-function-split" with "confval"
  Documentation/Functions/Split.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#1113 [BUGFIX] Remove noopener as superfluous
  Documentation/Functions/Typolink.rst
Labels: changelog, backport 11.5, backport 12.4

#1118 [TASK] Replace "t3-function-stdwrap" with "confval"
  Documentation/ContentObjects/Hmenu/Categories.rst
  Documentation/ContentObjects/UserAndUserInt/Index.rst
  Documentation/Functions/Data.rst
  Documentation/Functions/Encapslines.rst
  Documentation/Functions/Parsefunc.rst
  Documentation/Functions/Select.rst
  Documentation/Functions/Stdwrap.rst
  Documentation/Settings.cfg
  Documentation/Setup/Config/Index.rst
  Documentation/UsingSetting/Debugging.rst
  Documentation/UsingSetting/Register.rst
Labels: backport 12.4

#1115 [TASK] Update property information
  Documentation/ContentObjects/Fluidtemplate/Index.rst
Labels: backport 12.4

#1120 [TASK] Replace "t3-function-strpad" with "confval"
  Documentation/Functions/Strpad.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#1124 [BUGFIX] Correct outdated reference to typolink/forceAbsoluteUrl
  Documentation/Setup/Config/Index.rst
Labels: backport 12.4

#1123 [TASK] Replace "t3-function-tags" with "confval"
  Documentation/Functions/Tags.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#1127 [BUGFIX] Correct example about parseFunc.short
  Documentation/Functions/Parsefunc.rst
Labels: backport 11.5, backport 12.4

#1133 [TASK] Add ddev directory to gitignore
  .gitignore
Labels: backport 11.5, backport 12.4

#1134 [TASK] Set unique names for confvals in TMENU chapter
  Documentation/MenuObjects/Tmenu/Index.rst
  Documentation/MenuObjects/Tmenuitem/Index.rst
Labels: backport 12.4

#1132 [TASK] Set unique names for confvals in config chapter
  Documentation/Setup/Config/Index.rst
Labels: backport 12.4

#1135 [TASK] Set unique names for confvals in Gifbuilder chapter
  Documentation/Gifbuilder/ObjectNames/Adjust/Index.rst
  Documentation/Gifbuilder/ObjectNames/Box/Index.rst
  Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
  Documentation/Gifbuilder/ObjectNames/Effect/Index.rst
  Documentation/Gifbuilder/ObjectNames/Ellipse/Index.rst
  Documentation/Gifbuilder/ObjectNames/Emboss/Index.rst
  Documentation/Gifbuilder/ObjectNames/Image/Index.rst
  Documentation/Gifbuilder/ObjectNames/Outline/Index.rst
  Documentation/Gifbuilder/ObjectNames/Scale/Index.rst
  Documentation/Gifbuilder/ObjectNames/Shadow/Index.rst
  Documentation/Gifbuilder/ObjectNames/Text/Index.rst
  Documentation/Gifbuilder/ObjectNames/Workarea/Index.rst
  Documentation/Gifbuilder/Properties.rst
Labels: backport 12.4

#1140 [TASK] Set unique names for confvals in datatypes chapter
  Documentation/DataTypes/Index.rst
Labels: backport 11.5, backport 12.4

#1144 [TASK] Set unique names for confvals in Dataprocessor chapter
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/CommaSeparatedValueProcessor.rst
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/DatabaseQueryProcessor.rst
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/FilesProcessor.rst
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/FlexFormProcessor.rst
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/GalleryProcessor.rst
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/LanguageMenuProcessor.rst
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/MenuProcessor.rst
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/SiteLanguageProcessor.rst
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/SiteProcessor.rst
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/SplitProcessor.rst
Labels: backport 11.5, backport 12.4

#1143 [TASK] Set unique names for confvals in conditions chapter
  Documentation/Conditions/Index.rst
Labels: backport 11.5, backport 12.4

#1147 [TASK] Set unique names for confvals in cobjects chapter
  Documentation/ContentObjects/Case/Index.rst
  Documentation/ContentObjects/CoaAndCoaInt/Index.rst
  Documentation/ContentObjects/Content/Index.rst
  Documentation/ContentObjects/Extbaseplugin/Index.rst
  Documentation/ContentObjects/Files/Index.rst
  Documentation/ContentObjects/Fluidtemplate/Index.rst
  Documentation/ContentObjects/Hmenu/Index.rst
  Documentation/ContentObjects/Image/Index.rst
  Documentation/ContentObjects/ImgResource/Index.rst
  Documentation/ContentObjects/LoadRegister/Index.rst
  Documentation/ContentObjects/Records/Index.rst
  Documentation/ContentObjects/Svg/Index.rst
  Documentation/ContentObjects/Text/Index.rst
  Documentation/ContentObjects/UserAndUserInt/Index.rst
Labels: backport 11.5, backport 12.4

#1153 [BUGFIX] Fix references to confvals
  Documentation/DataTypes/Index.rst
Labels: backport 11.5, backport 12.4

#1154 [TASK] Switch to PHP-based rendering
  .github/workflows/test-documentation.yml
  Documentation/ContentObjects/Fluidtemplate/DataProcessing.rst
  Documentation/Includes.rst.txt
  Documentation/Index.rst
  Documentation/Settings.cfg
  Documentation/genindex.rst
  Documentation/guides.xml
  Documentation/screenshots.json
  Makefile
Labels: backport-required

#1159 [BUGFIX] Remove citation from around table
  Documentation/ContentObjects/Fluidtemplate/DataProcessing/FilesProcessor.rst
Labels: backport 11.5, backport 12.4

#1163 [TASK] Show full conditions in examples
  Documentation/Conditions/Index.rst
Labels: backport 12.4
