Repository TYPO3-Documentation/TYPO3CMS-Reference-Typoscript, pull requests merged in 2024-10, with the labels that each got.

#1347 [TASK] Use --minimal-test CLI option for documentation tests
  .github/workflows/test-documentation.yml
  Makefile
Labels: backport 11.5, backport 12.4

#1345 [TASK] Add example: Display an Extbase plugin in a Fluid template
  Documentation/ContentObjects/Extbaseplugin/Index.rst
  Documentation/ContentObjects/Extbaseplugin/_CodeSnippets/_MyController.php
  Documentation/ContentObjects/Extbaseplugin/_CodeSnippets/_SomeTemplate.html
  Documentation/ContentObjects/Extbaseplugin/_CodeSnippets/_configurePlugin.php
  Documentation/ContentObjects/Extbaseplugin/_CodeSnippets/_libMyPlugin.typoscript
Labels: backport 12.4

#1351 Add a contents menu for Reserved TLOs
  Documentation/TopLevelObjects/Other.rst
Labels: backport 12.4

#1355 [TASK] Display data processor aliases more prominent
  Documentation/DataProcessing/CommaSeparatedValueProcessor.rst
  Documentation/DataProcessing/CustomDataProcessors.rst
  Documentation/DataProcessing/DatabaseQueryProcessor.rst
  Documentation/DataProcessing/FilesProcessor.rst
  Documentation/DataProcessing/FlexFormProcessor.rst
  Documentation/DataProcessing/GalleryProcessor.rst
  Documentation/DataProcessing/Index.rst
  Documentation/DataProcessing/LanguageMenuProcessor.rst
  Documentation/DataProcessing/MenuProcessor.rst
  Documentation/DataProcessing/PageContentFetchingProcessor.rst
  Documentation/DataProcessing/RecordTransformationProcessor.rst
  Documentation/DataProcessing/SiteLanguageProcessor.rst
  Documentation/DataProcessing/SiteProcessor.rst
  Documentation/DataProcessing/SplitProcessor.rst
  Documentation/TopLevelObjects/Config.rst
Labels: backport 12.4, backport 13.4

#1358 [TASK] Introduce confval menues for processor options
  Documentation/DataProcessing/CommaSeparatedValueProcessor.rst
  Documentation/DataProcessing/DatabaseQueryProcessor.rst
  Documentation/DataProcessing/FilesProcessor.rst
  Documentation/DataProcessing/FlexFormProcessor.rst
  Documentation/DataProcessing/GalleryProcessor.rst
  Documentation/DataProcessing/LanguageMenuProcessor.rst
  Documentation/DataProcessing/MenuProcessor.rst
  Documentation/DataProcessing/PageContentFetchingProcessor.rst
  Documentation/DataProcessing/RecordTransformationProcessor.rst
  Documentation/DataProcessing/SiteLanguageProcessor.rst
  Documentation/DataProcessing/SiteProcessor.rst
  Documentation/DataProcessing/SplitProcessor.rst
Labels: backport 12.4, backport 13.4

#1360 [TASK] Use Core .editorconfig
  .editorconfig
Labels: backport 12.4, backport 13.4

#1363 [TASK] Update codesnippets
  Documentation/CodeSnippets/Config/Menus.php
  Documentation/CodeSnippets/DataProcessing/DataProcessingTemplates.rst.txt
  Documentation/CodeSnippets/DataProcessing/Template/DataProcCsv.rst.txt
  Documentation/CodeSnippets/DataProcessing/Template/DataProcCustom.rst.txt
  Documentation/CodeSnippets/DataProcessing/Template/DataProcDb.rst.txt
  Documentation/CodeSnippets/DataProcessing/Template/DataProcFiles.rst.txt
  Documentation/CodeSnippets/DataProcessing/Template/DataProcGallery.rst.txt
  Documentation/CodeSnippets/DataProcessing/Template/DataProcLangMenu.rst.txt
  Documentation/CodeSnippets/DataProcessing/Template/DataProcMenu.rst.txt
  Documentation/CodeSnippets/DataProcessing/Template/DataProcSite.rst.txt
  Documentation/CodeSnippets/DataProcessing/Template/DataProcSiteLanguage.rst.txt
  Documentation/CodeSnippets/DataProcessing/Template/DataProcSplit.rst.txt
  Documentation/CodeSnippets/DataProcessing/TypoScript/CommaSeparatedValueProcessor.rst.txt
  Documentation/CodeSnippets/DataProcessing/TypoScript/CustomCategoryProcessor.rst.txt
  Documentation/CodeSnippets/DataProcessing/TypoScript/DatabaseQueryProcessor.rst.txt
  Documentation/CodeSnippets/DataProcessing/TypoScript/FilesProcessor.rst.txt
  Documentation/CodeSnippets/DataProcessing/TypoScript/GalleryProcessor.rst.txt
  Documentation/CodeSnippets/DataProcessing/TypoScript/LanguageMenuProcessor.rst.txt
  Documentation/CodeSnippets/DataProcessing/TypoScript/MenuProcessor.rst.txt
  Documentation/CodeSnippets/DataProcessing/TypoScript/SiteLanguageProcessor.rst.txt
  Documentation/CodeSnippets/DataProcessing/TypoScript/SiteProcessor.rst.txt
  Documentation/CodeSnippets/DataProcessing/TypoScript/SplitProcessor.rst.txt
  Documentation/CodeSnippets/Menu/Template/BreadcrumbDataProcessor.rst.txt
  Documentation/CodeSnippets/Menu/Template/MenuCategorizedPages.rst.txt
  Documentation/CodeSnippets/Menu/Template/MenuPages.rst.txt
  Documentation/CodeSnippets/Menu/Template/MenuRecentlyUpdated.rst.txt
  Documentation/CodeSnippets/Menu/Template/MenuRelatedPages.rst.txt
  Documentation/CodeSnippets/Menu/Template/MenuSubpages.rst.txt
  Documentation/CodeSnippets/Menu/TypoScript/BreadcrumbDataProcessor.rst.txt
  Documentation/CodeSnippets/Menu/TypoScript/BreadcrumbLib.rst.txt
  Documentation/CodeSnippets/Menu/TypoScript/LanguageMenuLib.rst.txt
  Documentation/CodeSnippets/Menu/TypoScript/MenuCategorizedPages.rst.txt
  Documentation/CodeSnippets/Menu/TypoScript/MenuPages.rst.txt
  Documentation/CodeSnippets/Menu/TypoScript/MenuRecentlyUpdated.rst.txt
  Documentation/CodeSnippets/Menu/TypoScript/MenuRelatedPages.rst.txt
  Documentation/CodeSnippets/Menu/TypoScript/MenuSubpages.rst.txt
  Documentation/CodeSnippets/Menu/TypoScript/RelPrevNextMenu.rst.txt
  Documentation/ContentObjects/Hmenu/Browse.rst
  Documentation/ContentObjects/Hmenu/Language.rst
  Documentation/ContentObjects/Hmenu/Rootline.rst
  Documentation/ContentObjects/Hmenu/_code-snippets/_BreadcrumbDataProcessor.typoscript
  Documentation/ContentObjects/Hmenu/_code-snippets/_BreadcrumbLib.typoscript
  Documentation/ContentObjects/Hmenu/_code-snippets/_LanguageMenuLib.typoscript
  Documentation/ContentObjects/Hmenu/_code-snippets/_RelPrevNextMenu.typoscript
Labels: backport 13.4

#1366 [TASK] #105230 - Declare TypoScriptFrontendController deprecated
  Documentation/AppendixA/Index.rst
Labels: changelog, backport 13.4

#1369 [TASK] Remove outdated warning from FLUIDTEMPLATE.template
  Documentation/ContentObjects/Fluidtemplate/Index.rst
Labels: backport 13.4

#1357 [TASK] Remove TYPO3 v12.4 related version hints
  Documentation/Conditions/Index.rst
  Documentation/ContentObjects/Extbaseplugin/Index.rst
  Documentation/ContentObjects/Fluidtemplate/Index.rst
  Documentation/ContentObjects/Hmenu/Tmenu/Index.rst
  Documentation/DataProcessing/CommaSeparatedValueProcessor.rst
  Documentation/DataProcessing/DatabaseQueryProcessor.rst
  Documentation/DataProcessing/FilesProcessor.rst
  Documentation/DataProcessing/FlexFormProcessor.rst
  Documentation/DataProcessing/GalleryProcessor.rst
  Documentation/DataProcessing/LanguageMenuProcessor.rst
  Documentation/DataProcessing/MenuProcessor.rst
  Documentation/DataProcessing/SiteLanguageProcessor.rst
  Documentation/DataProcessing/SiteProcessor.rst
  Documentation/DataProcessing/SplitProcessor.rst
  Documentation/Functions/Data.rst
  Documentation/Functions/If.rst
  Documentation/Functions/Stdwrap.rst
  Documentation/Functions/Typolink.rst
  Documentation/TopLevelObjects/Config.rst
  Documentation/TopLevelObjects/Module.rst
  Documentation/TopLevelObjects/Page/Index.rst
  Documentation/TopLevelObjects/Plugin.rst
  Documentation/UsingSetting/Constants.rst
  Documentation/UsingSetting/Debugging.rst
  Documentation/UsingSetting/Entering.rst
  Documentation/UsingSetting/TheConstantEditor.rst
Labels: backport 13.4

#1374 [TASK] Move TypoScript 45 Guide into TypoScript reference
  Documentation/Guide/CreateAMenu/Index.rst
  Documentation/Guide/HtmlTemplate/Index.rst
  Documentation/Guide/Index.rst
  Documentation/Guide/NextSteps/Index.rst
  Documentation/Guide/ReadingContentRecords/ContentElements/Index.rst
  Documentation/Guide/ReadingContentRecords/Index.rst
  Documentation/Guide/TypoScriptFunctions/If/Index.rst
  Documentation/Guide/TypoScriptFunctions/ImgResource/Index.rst
  Documentation/Guide/TypoScriptFunctions/Index.rst
  Documentation/Guide/TypoScriptFunctions/ParseFunc/Index.rst
  Documentation/Guide/TypoScriptFunctions/Select/Index.rst
  Documentation/Guide/TypoScriptFunctions/Split/Index.rst
  Documentation/Guide/TypoScriptFunctions/Typolink/Index.rst
  Documentation/Guide/TypoScriptObjects/DatabaseQueries/Index.rst
  Documentation/Guide/TypoScriptObjects/FurtherObjects/Index.rst
  Documentation/Guide/TypoScriptObjects/Index.rst
  Documentation/Guide/TypoScriptObjects/RenderingContent/Index.rst
  Documentation/Guide/TypoScriptOverview/BackendConfiguration/Index.rst
  Documentation/Guide/TypoScriptOverview/FirstSteps/Index.rst
  Documentation/Guide/TypoScriptOverview/Index.rst
  Documentation/Guide/TypoScriptOverview/MainTemplate/Index.rst
  Documentation/Guide/TypoScriptOverview/Prerequisites/Index.rst
  Documentation/Guide/TypoScriptOverview/TheTermTemplate/Index.rst
  Documentation/Guide/TypoScriptOverview/TypoScriptAnArray/Index.rst
  Documentation/Guide/TypoScriptOverview/WhyTypoScript/Index.rst
  Documentation/Guide/UsingFluidStyledContent/Index.rst
  Documentation/Guide/UsingGetText/Index.rst
  Documentation/Guide/UsingStdWrap/CObject/Index.rst
  Documentation/Guide/UsingStdWrap/HeedTheOrder/Index.rst
  Documentation/Guide/UsingStdWrap/Index.rst
  Documentation/Guide/UsingStdWrap/ModifyTheOrder/Index.rst
  Documentation/Guide/UsingStdWrap/TheDataType/Index.rst
  Documentation/Images/AutomaticScreenshots/RootlevelFlag.png
  Documentation/Images/AutomaticScreenshots/RootlevelFlag.rst.txt
  Documentation/Images/AutomaticScreenshots/TemplateAnalyzerStructure.png
  Documentation/Images/AutomaticScreenshots/TemplateAnalyzerStructure.rst.txt
  Documentation/Images/ManualScreenshots/NoTypoScriptTemplateFound.png
  Documentation/Images/ManualScreenshots/NoTypoScriptTemplateFoundDebuggingOff.png
  Documentation/Images/ManualScreenshots/ThePageIsNotConfigured.png
  Documentation/Index.rst
Labels: backport 12.4, backport 13.4

#1380 [BUGFIX] Fix links to the TypoScript Guide
  Documentation/About.rst
  Documentation/Index.rst
  Documentation/Introduction/Index.rst
Labels: backport 12.4, backport 13.4

#1372 [TASK] Improve `page-content` data processor description
  Documentation/DataProcessing/PageContentFetchingProcessor.rst
  Documentation/DataProcessing/_PageContentFetchingProcessor/_Default.html
Labels: backport 13.4

#1384 [TASK] Make TypoScript documentation clearer and more consistent
  Documentation/Guide/Images/AutomaticScreenshots/RootlevelFlag.png
  Documentation/Guide/Images/AutomaticScreenshots/RootlevelFlag.rst.txt
  Documentation/Guide/Images/AutomaticScreenshots/TemplateAnalyzerStructure.png
  Documentation/Guide/Images/AutomaticScreenshots/TemplateAnalyzerStructure.rst.txt
  Documentation/Guide/Images/ManualScreenshots/ModuleNameTypoScript.png
  Documentation/Guide/Images/ManualScreenshots/NoTypoScriptTemplateFound.png
  Documentation/Guide/Images/ManualScreenshots/NoTypoScriptTemplateFoundDebuggingOff.png
  Documentation/Guide/Images/ManualScreenshots/ThePageIsNotConfigured.png
  Documentation/Guide/ReadingContentRecords/ContentElements/Index.rst
  Documentation/Guide/TypoScriptFunctions/ImgResource/Index.rst
  Documentation/Guide/TypoScriptFunctions/Typolink/Index.rst
  Documentation/Guide/TypoScriptObjects/RenderingContent/Index.rst
  Documentation/Guide/TypoScriptOverview/FirstSteps/Index.rst
  Documentation/Guide/TypoScriptOverview/TheTermTemplate/Index.rst
  Documentation/Guide/TypoScriptOverview/WhyTypoScript/Index.rst
  Documentation/Guide/UsingStdWrap/CObject/Index.rst
  Documentation/Guide/UsingStdWrap/HeedTheOrder/Index.rst
Labels: backport 12.4, backport 13.4

#1387 [TASK] Unify headlines
  Documentation/Guide/CreateAMenu/Index.rst
  Documentation/Guide/NextSteps/Index.rst
  Documentation/Guide/ReadingContentRecords/ContentElements/Index.rst
  Documentation/Guide/ReadingContentRecords/Index.rst
  Documentation/Guide/TypoScriptFunctions/If/Index.rst
  Documentation/Guide/TypoScriptFunctions/ImgResource/Index.rst
  Documentation/Guide/TypoScriptFunctions/Index.rst
  Documentation/Guide/TypoScriptFunctions/Split/Index.rst
  Documentation/Guide/TypoScriptFunctions/Typolink/Index.rst
  Documentation/Guide/TypoScriptObjects/DatabaseQueries/Index.rst
  Documentation/Guide/TypoScriptObjects/FurtherObjects/Index.rst
  Documentation/Guide/TypoScriptObjects/RenderingContent/Index.rst
  Documentation/Guide/TypoScriptOverview/BackendConfiguration/Index.rst
  Documentation/Guide/TypoScriptOverview/FirstSteps/Index.rst
  Documentation/Guide/TypoScriptOverview/Index.rst
  Documentation/Guide/TypoScriptOverview/MainTemplate/Index.rst
  Documentation/Guide/TypoScriptOverview/Prerequisites/Index.rst
  Documentation/Guide/TypoScriptOverview/TheTermTemplate/Index.rst
  Documentation/Guide/TypoScriptOverview/TypoScriptAnArray/Index.rst
  Documentation/Guide/TypoScriptOverview/WhyTypoScript/Index.rst
  Documentation/Guide/UsingFluidStyledContent/Index.rst
  Documentation/Guide/UsingGetText/Index.rst
  Documentation/Guide/UsingStdWrap/CObject/Index.rst
  Documentation/Guide/UsingStdWrap/HeedTheOrder/Index.rst
  Documentation/Guide/UsingStdWrap/Index.rst
  Documentation/Guide/UsingStdWrap/ModifyTheOrder/Index.rst
Labels: backport 12.4, backport 13.4

#1378 [TASK] Avoid TSFE->page in Data chapter
  Documentation/Functions/Data.rst
Labels: backport 13.4

#1379 Add information on how to access site settings
  Documentation/ContentObjects/Pageview/Index.rst
Labels: backport 13.4

#1377 [TASK] #90522 - Remove TSFE->lastImageInfo in IMAGE cObj chapter
  Documentation/ContentObjects/Image/Index.rst
Labels: backport 12.4, backport 13.4
