Repository TYPO3-Documentation/TYPO3CMS-Reference-Typoscript, pull requests merged in 2024-07, with the labels that each got.

#1295 [BUGFIX] Fix links to viewhlepers
  Documentation/ContentObjects/Fluidtemplate/Index.rst
  Documentation/ContentObjects/Pageview/Index.rst
Labels: backport 12.4

#1301 Correct wording in Plugin.rst
  Documentation/TopLevelObjects/Plugin.rst
Labels: backport 11.5, backport 12.4

#1306 [TASK] No Frontend TypoScript based template overrides in the backend
  Documentation/TopLevelObjects/Module.rst
Labels: backport 12.4

#1308 [TASK] Add hint to concatenate/compress options
  Documentation/TopLevelObjects/Config.rst
  Documentation/TopLevelObjects/_includes/_concat-compress.rst.txt
Labels: content clarification, backport 11.5, backport 12.4

#1311 [TASK] Fix indentations
  Documentation/Conditions/Index.rst
Labels: backport 11.5, backport 12.4
